services:
  homeassistant:
    container_name: nwp500
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./custom_components:/config/custom_components
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
